//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _404Project.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttractionComment
    {
        public int Id { get; set; }
        public Nullable<int> AttractionId { get; set; }
        public string Text { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Attraction Attraction { get; set; }
    }
}
