//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _404Project.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GidHelper
    {
        public int Id { get; set; }
        public Nullable<int> GIDId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    }
}
