//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _404Project.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class itkotdbEntities4 : DbContext
    {
        public itkotdbEntities4()
            : base("name=itkotdbEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attraction> Attraction { get; set; }
        public virtual DbSet<AttractionComment> AttractionComment { get; set; }
        public virtual DbSet<AttractionImage> AttractionImage { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<GidHelper> GidHelper { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductComment> ProductComment { get; set; }
        public virtual DbSet<ProductImage> ProductImage { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<TourComment> TourComment { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
